import type { Metadata } from 'next';
import localFont from 'next/font/local'
import './globals.css';
import { getServerSession } from 'next-auth';
import AuthProvider from '@/utils/SessionProvider';
import { ThemeProvider } from '@/components/ThemeProvider';


const urbanist = localFont({
  src: '../../public/font/Urbanist-Regular.woff2'
})
export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider session={session}>
        <body className={`${urbanist.className} bg-[#f1f1f1] dark:bg-[#212121]`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  )
}
 